spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect # MyIsam은 @Transaction 발동이 안됨.  그래서 InnoDB 스토리지 엔진을 사용한 것으로 변경


  profiles:
    include:
      - oauth
      - key
      - jwt
      - mail
    active: prod
