spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect # MyIsam은 @Transaction 발동이 안됨.  그래서 InnoDB 스토리지 엔진을 사용한 것으로 변경
  pid:
    file: /home/ec2-user/app/step2/ItNovation.pid

  profiles:
    include:
      - oauth
      - key
      - jwt
      - mail
    active: prod

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    path: /swagger-ui
  paths-to-match:
    - /**
logging:
  level:
    web: debug
