spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect


  profiles:
    include:
      - oauth
      - ttkey
      - jwt
      - mail
    active: prod

